# Generated by Django 3.2.8 on 2021-10-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_hotel_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_details',
            name='Description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
