# Generated by Django 3.2.8 on 2021-10-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_hotel_details_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_details',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
